---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgAjxuQbg3ReBbQWIMQ4I+zVwvQE1MFPMDUl/ie9ijXE9wqYdynCwYmUu18um6R2HjnMVGVv0U9PGoMSkL15xDaNMwfm2Z2E6mTRiIWOdVpJK+P2vG0Qx79FNBjx7yaXJ5AD8qoMabD1zYUXPU6AX7D5w4VtKwbtNmPf51rgaaJkpPXURG17FSoyqeoUEISY2H8a2Y8DM2TjRTumg/Ve7IlsjOm0qWzDNs5oe33i5hoLqhVhMtV64O3FXbdxdXYtieiStxOZ11lDOe5e83ATAnhfNvBL3nBxhlJXsGFqSAuLY8VnHhRJJ1YbwsMf8Nj8A0bNqWt63cs5VDvI53TRKSQkEq+jjuoQbejQfk9kC3CrqLP2Wk5rOpJfjwG/EwK5QevmW1o9sV/n7OX/WcLa6RN59MSSAsw+80Xon4spYJ8VRM/QDzq96oizsQWtl3qLNb2HUjZtuPC57cuoELzn6ZZ4vTbZk3VHvLSBJv17oFzXS7lfy5Dfjz3z50c0Ra2gOOnE08FP/G9oANPl1G/6EJnqCRHyETq14erqhIXJ9v96xhajh2OaOsFqRteoARM+rodqxOUa1ONyZ6EZXqbav0lYaJw8MfzBNtuNnFgtacTopFlnS041N6a6urVIdgYSZjJrQzGP64/cvaBCin6CYQPX9mVy507FLh5elNGWdYOC93dpwqYlKWux0M6taszbjspSX+x11m/LMX+abfVSZLrVmZ70nfiRlcdS
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database
